"""Decide whether a set of captions was machine generated or human edited.

Panopto exposes captions through several endpoints and the shape of the payload
differs between Panopto releases and between the public REST API, the viewer's
``DeliveryInfo`` response, and a downloaded SRT file. Rather than depending on a
single field name, this module scores every signal it can find and reports the
evidence it used, so a reviewer can audit the verdict:

* **Metadata signals** - any key anywhere in the payload whose name looks like
  an ASR/machine/auto flag, an upload/import flag, or an edited flag. These are
  authoritative when present.
* **Text signals** - characteristics of the caption text itself. Human
  captioners add speaker labels (``>>``), non-speech cues (``[MUSIC]``), and
  full punctuation; raw speech recognition output generally has none of those.

Everything here is pure Python with no network access so it can be unit tested.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from auditCore import CAPTION_AUTO, CAPTION_HUMAN, CAPTION_NONE, CAPTION_UNKNOWN

# Weights are additive. Negative scores point at machine generated captions,
# positive scores at human authored or human corrected captions.
_METADATA_WEIGHT = 6.0
_STRONG_TEXT_WEIGHT = 2.5
_WEAK_TEXT_WEIGHT = 1.0
_DECISION_THRESHOLD = 2.0

# Key names that flag machine generated captions when truthy.
_AUTO_KEY_HINTS = (
    "machinetranscription",
    "machinegenerated",
    "isautogenerated",
    "autogenerated",
    "isautomatic",
    "automaticcaption",
    "speechrecognition",
    "isasr",
    "asrcaption",
)

# Key names that flag human supplied captions when truthy.
_HUMAN_KEY_HINTS = (
    "isedited",
    "hasbeenedited",
    "humanedited",
    "manuallyedited",
    "iscaptionedited",
    "uploadedcaption",
    "importedcaption",
    "isuploaded",
    "hasuploadedcaptions",
)

# Keys whose *value* describes where the captions came from.
_SOURCE_KEY_HINTS = (
    "captiontype",
    "captionsource",
    "captionorigin",
    "captionservice",
    "transcriptiontype",
    "transcriptionsource",
    "sourcetype",
    "generatedby",
    "provider",
    "service",
    "origin",
)

_AUTO_VALUE_HINTS = (
    "asr",
    "machine",
    "auto",
    "speech",
    "automatic",
    "generated",
)

_HUMAN_VALUE_HINTS = (
    "upload",
    "import",
    "manual",
    "human",
    "professional",
    "vendor",
    "ordered",
    "edited",
    "verbit",
    "rev.com",
    "3play",
)

_SPEAKER_LABEL = re.compile(r"(^|\n)\s*(>>|-\s?>>|[A-Z][A-Za-z .'-]{1,24}:)")
_NON_SPEECH_CUE = re.compile(r"[\[\(](?:[^\]\)]{1,40})[\]\)]")
_MUSIC_NOTE = re.compile(r"[♪♫♬♩]")
_INAUDIBLE = re.compile(r"\[(?:inaudible|crosstalk|unintelligible)\]", re.IGNORECASE)
_SENTENCE_END = re.compile(r"[.!?]['\"”’)\]]?\s*$")
_HTML_TAG = re.compile(r"<[^>]+>")
_SRT_INDEX = re.compile(r"^\d+$")
_SRT_TIMECODE = re.compile(r"\d{1,2}:\d{2}:\d{2}[,.]\d{1,3}\s*-->")


@dataclass
class CaptionClassification:
    """Verdict for one video's captions."""

    kind: str = CAPTION_UNKNOWN
    confidence: str = "low"
    signals: List[str] = field(default_factory=list)
    language: Optional[str] = None
    method: Optional[str] = None
    score: float = 0.0

    @property
    def hasCaptions(self) -> bool:
        return self.kind != CAPTION_NONE

    def asDict(self) -> Dict[str, Any]:
        """Shape written into ``data/audited_videos.json``."""

        return {
            "caption_kind": self.kind,
            "caption_confidence": self.confidence,
            "caption_signals": self.signals,
            "caption_language": self.language,
            "caption_detection_method": self.method,
        }


# ----------------------------------------------------------------------
# payload helpers
def iterPairs(payload: Any, prefix: str = "") -> Iterable[Tuple[str, Any]]:
    """Yield ``(dotted_key, value)`` for every scalar inside ``payload``."""

    if isinstance(payload, dict):
        for key, value in payload.items():
            child = f"{prefix}.{key}" if prefix else str(key)
            yield from iterPairs(value, child)
    elif isinstance(payload, (list, tuple)):
        for index, value in enumerate(payload):
            child = f"{prefix}[{index}]"
            yield from iterPairs(value, child)
    else:
        yield prefix, payload


def _isTruthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    if isinstance(value, str):
        return value.strip().lower() in {"true", "yes", "1", "y"}
    return False


def _isFalsey(value: Any) -> bool:
    if isinstance(value, bool):
        return not value
    if isinstance(value, str):
        return value.strip().lower() in {"false", "no", "0", "n"}
    return False


def extractCaptionText(payload: Any) -> List[str]:
    """Pull caption cue strings out of an arbitrary Panopto payload."""

    if payload is None:
        return []

    if isinstance(payload, str):
        return parseSrt(payload)

    cues: List[str] = []
    for key, value in iterPairs(payload):
        if not isinstance(value, str):
            continue

        leaf = key.split(".")[-1].split("[")[0].lower()
        if leaf in {"caption", "captiontext", "text", "content", "value", "line"}:
            cleaned = _HTML_TAG.sub("", value).strip()
            if cleaned:
                cues.append(cleaned)

    return cues


def parseSrt(text: str) -> List[str]:
    """Return the spoken lines of an SRT/WebVTT document."""

    cues: List[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.upper() == "WEBVTT":
            continue
        if _SRT_INDEX.match(line) or _SRT_TIMECODE.search(line):
            continue
        cleaned = _HTML_TAG.sub("", line).strip()
        if cleaned:
            cues.append(cleaned)

    return cues


def extractLanguage(payload: Any) -> Optional[str]:
    """Best effort caption language from a Panopto payload."""

    if not isinstance(payload, (dict, list, tuple)):
        return None

    for key, value in iterPairs(payload):
        if not isinstance(value, str) or not value.strip():
            continue

        leaf = key.split(".")[-1].split("[")[0].lower()
        if leaf in {"language", "languagename", "captionlanguage", "locale"}:
            return value.strip()

    return None


# ----------------------------------------------------------------------
# scoring
def _scoreMetadata(payload: Any) -> Tuple[float, List[str]]:
    score = 0.0
    signals: List[str] = []

    if not isinstance(payload, (dict, list, tuple)):
        return score, signals

    for key, value in iterPairs(payload):
        leaf = key.split(".")[-1].split("[")[0].lower()

        if any(hint in leaf for hint in _AUTO_KEY_HINTS):
            if _isTruthy(value):
                score -= _METADATA_WEIGHT
                signals.append(f"metadata:{key}={value} (machine generated flag)")
            elif _isFalsey(value):
                score += _WEAK_TEXT_WEIGHT
                signals.append(f"metadata:{key}={value} (machine flag explicitly off)")
            continue

        if any(hint in leaf for hint in _HUMAN_KEY_HINTS):
            if _isTruthy(value):
                score += _METADATA_WEIGHT
                signals.append(f"metadata:{key}={value} (edited/uploaded flag)")
            continue

        if any(hint in leaf for hint in _SOURCE_KEY_HINTS) and isinstance(value, str):
            lowered = value.strip().lower()
            if not lowered:
                continue
            if any(hint in lowered for hint in _HUMAN_VALUE_HINTS):
                score += _METADATA_WEIGHT
                signals.append(f"metadata:{key}={value} (human caption source)")
            elif any(hint in lowered for hint in _AUTO_VALUE_HINTS):
                score -= _METADATA_WEIGHT
                signals.append(f"metadata:{key}={value} (machine caption source)")

    return score, signals


def _scoreText(cues: Sequence[str]) -> Tuple[float, List[str]]:
    """Score caption text. Negative means machine generated, positive human."""

    score = 0.0
    signals: List[str] = []

    cues = [cue for cue in cues if cue and cue.strip()]
    if not cues:
        return score, signals

    joined = "\n".join(cues)
    letters = [ch for ch in joined if ch.isalpha()]

    # Markers a speech recognition engine never produces on its own. Their
    # presence is close to proof that a person wrote or corrected the file.
    explicit_human = False

    if _SPEAKER_LABEL.search(joined):
        score += _STRONG_TEXT_WEIGHT
        explicit_human = True
        signals.append("text: speaker labels present (typical of edited captions)")

    if _MUSIC_NOTE.search(joined) or _NON_SPEECH_CUE.search(joined):
        score += _STRONG_TEXT_WEIGHT
        explicit_human = True
        signals.append("text: non-speech cues present (typical of edited captions)")

    if _INAUDIBLE.search(joined):
        score += _WEAK_TEXT_WEIGHT
        explicit_human = True
        signals.append("text: transcription markers such as [inaudible] present")

    if explicit_human:
        # The remaining checks describe writing style, which is far weaker
        # evidence than the markers above; applying them here would let a
        # lowercase transcript cancel out proof of human authoring.
        return score, signals

    # Speech recognition output is usually punctuation-light and, in older
    # Panopto releases, entirely lowercase.
    if letters and not any(ch.isupper() for ch in letters):
        score -= _STRONG_TEXT_WEIGHT
        signals.append("text: no capital letters anywhere (typical of raw ASR)")

    terminated = sum(1 for cue in cues if _SENTENCE_END.search(cue))
    terminated_ratio = terminated / len(cues)
    has_commas = "," in joined

    if len(cues) >= 4:
        if terminated_ratio <= 0.05 and not has_commas:
            score -= _STRONG_TEXT_WEIGHT
            signals.append("text: cues carry no sentence punctuation (typical of raw ASR)")
        elif terminated_ratio >= 0.35:
            score += _WEAK_TEXT_WEIGHT
            signals.append(
                f"text: {terminated_ratio:.0%} of cues end in sentence punctuation"
            )

    return score, signals


def _confidenceFor(score: float, metadata_decisive: bool) -> str:
    if metadata_decisive:
        return "high"
    magnitude = abs(score)
    if magnitude >= _STRONG_TEXT_WEIGHT * 2:
        return "medium"
    return "low"


def classifyCaptions(
    metadata: Any = None,
    cues: Optional[Sequence[str]] = None,
    method: Optional[str] = None,
) -> CaptionClassification:
    """Classify captions from Panopto metadata and/or caption text.

    Args:
        metadata: any JSON payload Panopto returned (REST API caption list,
            viewer ``DeliveryInfo`` response, session details, ...).
        cues: caption lines. When omitted they are extracted from ``metadata``.
        method: label describing where the data came from, recorded in the
            result for traceability.

    Returns:
        A :class:`CaptionClassification` describing the verdict, the confidence,
        and every signal that contributed to it.
    """

    if cues is None:
        cues = extractCaptionText(metadata)

    cues = [cue for cue in cues if isinstance(cue, str) and cue.strip()]

    metadata_score, metadata_signals = _scoreMetadata(metadata)
    text_score, text_signals = _scoreText(cues)

    signals = metadata_signals + text_signals
    score = metadata_score + text_score

    language = extractLanguage(metadata)
    metadata_decisive = abs(metadata_score) >= _METADATA_WEIGHT

    if not cues and not metadata_signals:
        return CaptionClassification(
            kind=CAPTION_NONE,
            confidence="high" if metadata is not None else "low",
            signals=signals or ["no caption data returned"],
            language=language,
            method=method,
            score=0.0,
        )

    if metadata_decisive:
        # Panopto told us outright where the captions came from; writing style
        # cannot outvote that. A disagreement is still worth recording because
        # it usually means ASR output that someone later corrected.
        kind = CAPTION_AUTO if metadata_score < 0 else CAPTION_HUMAN
        if text_score and (text_score < 0) != (metadata_score < 0):
            signals.append(
                "note: caption text disagrees with the metadata flag "
                "(captions may have been generated then edited)"
            )
    elif score <= -_DECISION_THRESHOLD:
        kind = CAPTION_AUTO
    elif score >= _DECISION_THRESHOLD:
        kind = CAPTION_HUMAN
    else:
        kind = CAPTION_UNKNOWN
        if not signals:
            signals = ["captions found but no distinguishing signals"]

    return CaptionClassification(
        kind=kind,
        confidence=_confidenceFor(score, metadata_decisive),
        signals=signals,
        language=language,
        method=method,
        score=round(score, 2),
    )


def mergeClassifications(
    *classifications: Optional[CaptionClassification],
) -> CaptionClassification:
    """Pick the most trustworthy verdict from several detection attempts.

    Higher confidence wins; ties are broken by the larger absolute score so a
    verdict backed by more evidence beats a borderline one.
    """

    ranking = {"high": 3, "medium": 2, "low": 1}
    best: Optional[CaptionClassification] = None

    for candidate in classifications:
        if candidate is None:
            continue
        if candidate.kind in {CAPTION_UNKNOWN, CAPTION_NONE} and best is not None:
            # Only fall back to a vague verdict when nothing better exists.
            if best.kind not in {CAPTION_UNKNOWN, CAPTION_NONE}:
                continue
        if best is None:
            best = candidate
            continue

        candidate_rank = (ranking.get(candidate.confidence, 0), abs(candidate.score))
        best_rank = (ranking.get(best.confidence, 0), abs(best.score))
        if candidate_rank > best_rank:
            best = candidate

    return best or CaptionClassification()
