"""Tests for the Panopto caption source classifier."""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from auditCore import CAPTION_AUTO, CAPTION_HUMAN, CAPTION_NONE, CAPTION_UNKNOWN
from panoptoCaptions import (
    classifyCaptions,
    extractCaptionText,
    extractLanguage,
    mergeClassifications,
    parseSrt,
)

ASR_CUES = [
    "so today we're going to look at the second half of chapter four",
    "and then we'll work through a couple of the practice problems",
    "if you haven't done the reading yet make sure you do that first",
    "okay so let's start with the definition on slide twelve",
]

EDITED_CUES = [
    ">> INSTRUCTOR: Good morning, everyone.",
    "Today we are covering chapter four.",
    "[SOUND OF CHALK ON BOARD]",
    "Let's begin with the definition on slide twelve.",
]


class MetadataSignalTests(unittest.TestCase):
    def test_machineTranscriptionFlagIsAuthoritative(self):
        payload = {"Delivery": {"MachineTranscription": True, "Captions": []}}
        result = classifyCaptions(payload, cues=["Anything at all."])

        self.assertEqual(result.kind, CAPTION_AUTO)
        self.assertEqual(result.confidence, "high")
        self.assertTrue(any("MachineTranscription" in s for s in result.signals))

    def test_uploadedCaptionFlagMarksHumanSource(self):
        payload = {"Session": {"HasUploadedCaptions": True}}
        result = classifyCaptions(payload, cues=ASR_CUES)

        self.assertEqual(result.kind, CAPTION_HUMAN)
        self.assertEqual(result.confidence, "high")

    def test_captionSourceStringIsRead(self):
        self.assertEqual(
            classifyCaptions({"CaptionType": "ASR"}, cues=["Hello."]).kind,
            CAPTION_AUTO,
        )
        self.assertEqual(
            classifyCaptions({"CaptionSource": "Uploaded"}, cues=["Hello."]).kind,
            CAPTION_HUMAN,
        )

    def test_flagsAreFoundAtAnyNestingDepth(self):
        payload = {"a": [{"b": {"IsAutoGenerated": "true"}}]}
        self.assertEqual(classifyCaptions(payload, cues=["Hi."]).kind, CAPTION_AUTO)

    def test_falseAutoFlagDoesNotClassifyAsAuto(self):
        payload = {"MachineTranscription": False}
        self.assertNotEqual(classifyCaptions(payload, cues=EDITED_CUES).kind, CAPTION_AUTO)


class TextSignalTests(unittest.TestCase):
    def test_rawAsrTextIsDetected(self):
        result = classifyCaptions(None, cues=ASR_CUES)

        self.assertEqual(result.kind, CAPTION_AUTO)
        self.assertIn(result.confidence, {"medium", "low"})

    def test_editedTextIsDetected(self):
        result = classifyCaptions(None, cues=EDITED_CUES)

        self.assertEqual(result.kind, CAPTION_HUMAN)

    def test_speakerLabelsCountAsHumanEditing(self):
        result = classifyCaptions(None, cues=[">> welcome back", "lets keep going"])
        self.assertEqual(result.kind, CAPTION_HUMAN)

    def test_ambiguousTextIsReportedAsUnknown(self):
        result = classifyCaptions(None, cues=["Chapter four.", "Slide twelve"])

        self.assertEqual(result.kind, CAPTION_UNKNOWN)
        self.assertTrue(result.signals)

    def test_noCaptionDataMeansNoCaptions(self):
        result = classifyCaptions({"Captions": []}, cues=[])

        self.assertEqual(result.kind, CAPTION_NONE)
        self.assertFalse(result.hasCaptions)


class ExtractionTests(unittest.TestCase):
    def test_captionTextIsPulledFromNestedPayloads(self):
        payload = {"Delivery": {"Captions": [{"Caption": "one"}, {"Caption": "two"}]}}
        self.assertEqual(extractCaptionText(payload), ["one", "two"])

    def test_htmlTagsAreStripped(self):
        payload = [{"Caption": "<i>hello</i> there"}]
        self.assertEqual(extractCaptionText(payload), ["hello there"])

    def test_srtIsParsedIntoSpokenLines(self):
        srt = (
            "1\n00:00:01,000 --> 00:00:03,000\nGood morning, everyone.\n\n"
            "2\n00:00:03,000 --> 00:00:05,500\nToday we cover chapter four.\n"
        )
        self.assertEqual(
            parseSrt(srt),
            ["Good morning, everyone.", "Today we cover chapter four."],
        )

    def test_webvttHeaderIsIgnored(self):
        vtt = "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHello.\n"
        self.assertEqual(parseSrt(vtt), ["Hello."])

    def test_languageIsExtracted(self):
        self.assertEqual(
            extractLanguage({"Delivery": {"Captions": [{"LanguageName": "English"}]}}),
            "English",
        )

    def test_stringPayloadIsTreatedAsSrt(self):
        cues = extractCaptionText("1\n00:00:01,000 --> 00:00:02,000\nHi there.\n")
        self.assertEqual(cues, ["Hi there."])


class MergeTests(unittest.TestCase):
    def test_higherConfidenceWins(self):
        weak = classifyCaptions(None, cues=["Chapter four.", "Slide twelve"])
        strong = classifyCaptions({"MachineTranscription": True}, cues=["Hi."])

        self.assertEqual(mergeClassifications(weak, strong).kind, CAPTION_AUTO)
        self.assertEqual(mergeClassifications(strong, weak).kind, CAPTION_AUTO)

    def test_definiteVerdictBeatsUnknown(self):
        unknown = classifyCaptions(None, cues=["Chapter four.", "Slide twelve"])
        edited = classifyCaptions(None, cues=EDITED_CUES)

        self.assertEqual(mergeClassifications(edited, unknown).kind, CAPTION_HUMAN)

    def test_noneInputsYieldUnknown(self):
        self.assertEqual(mergeClassifications(None, None).kind, CAPTION_UNKNOWN)

    def test_resultSerialisesForTheResultsFile(self):
        entry = classifyCaptions({"MachineTranscription": True}, cues=["Hi."]).asDict()

        self.assertEqual(entry["caption_kind"], CAPTION_AUTO)
        self.assertIn("caption_confidence", entry)
        self.assertIn("caption_signals", entry)


if __name__ == "__main__":
    unittest.main()
